# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'py_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 436)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 511, 436))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.main_label = QtWidgets.QLabel(self.tab)
        self.main_label.setGeometry(QtCore.QRect(0, 0, 504, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.main_label.setFont(font)
        self.main_label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "border-radius: 5px;\n"
                                      "border-style: solid;\n"
                                      "border-width: 3px;\n"
                                      "border-color: rgb(192, 192, 192);")
        self.main_label.setObjectName("main_label")
        self.one_button = QtWidgets.QPushButton(self.tab)
        self.one_button.setGeometry(QtCore.QRect(0, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.one_button.setFont(font)
        self.one_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(255, 128, 0);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-style: grooved;\n"
                                      "    border-width: 2px;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(255, 153, 51);\n"
                                      "}")
        self.one_button.setObjectName("one_button")
        self.two_button = QtWidgets.QPushButton(self.tab)
        self.two_button.setGeometry(QtCore.QRect(77, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.two_button.setFont(font)
        self.two_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(255, 128, 0);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-style: grooved;\n"
                                      "    border-width: 2px;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(255, 153, 51);\n"
                                      "}")
        self.two_button.setObjectName("two_button")
        self.three_button = QtWidgets.QPushButton(self.tab)
        self.three_button.setGeometry(QtCore.QRect(154, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.three_button.setFont(font)
        self.three_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.three_button.setObjectName("three_button")
        self.four_button = QtWidgets.QPushButton(self.tab)
        self.four_button.setGeometry(QtCore.QRect(0, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.four_button.setFont(font)
        self.four_button.setStyleSheet("QPushButton {\n"
                                       "    background-color: rgb(255, 128, 0);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    border-style: grooved;\n"
                                       "    border-width: 2px;\n"
                                       "    border-radius: 5px;\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(255, 153, 51);\n"
                                       "}")
        self.four_button.setObjectName("four_button")
        self.five_button = QtWidgets.QPushButton(self.tab)
        self.five_button.setGeometry(QtCore.QRect(77, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.five_button.setFont(font)
        self.five_button.setStyleSheet("QPushButton {\n"
                                       "    background-color: rgb(255, 128, 0);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    border-style: grooved;\n"
                                       "    border-width: 2px;\n"
                                       "    border-radius: 5px;\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(255, 153, 51);\n"
                                       "}")
        self.five_button.setObjectName("five_button")
        self.six_button = QtWidgets.QPushButton(self.tab)
        self.six_button.setGeometry(QtCore.QRect(154, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.six_button.setFont(font)
        self.six_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(255, 128, 0);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-style: grooved;\n"
                                      "    border-width: 2px;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(255, 153, 51);\n"
                                      "}")
        self.six_button.setObjectName("six_button")
        self.seven_button = QtWidgets.QPushButton(self.tab)
        self.seven_button.setGeometry(QtCore.QRect(0, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.seven_button.setFont(font)
        self.seven_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.seven_button.setObjectName("seven_button")
        self.eight_button = QtWidgets.QPushButton(self.tab)
        self.eight_button.setGeometry(QtCore.QRect(77, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.eight_button.setFont(font)
        self.eight_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.eight_button.setObjectName("eight_button")
        self.nine_button = QtWidgets.QPushButton(self.tab)
        self.nine_button.setGeometry(QtCore.QRect(154, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.nine_button.setFont(font)
        self.nine_button.setStyleSheet("QPushButton {\n"
                                       "    background-color: rgb(255, 128, 0);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    border-style: grooved;\n"
                                       "    border-width: 2px;\n"
                                       "    border-radius: 5px;\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(255, 153, 51);\n"
                                       "}")
        self.nine_button.setObjectName("nine_button")
        self.plius_button = QtWidgets.QPushButton(self.tab)
        self.plius_button.setGeometry(QtCore.QRect(276, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.plius_button.setFont(font)
        self.plius_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.plius_button.setObjectName("plius_button")
        self.del_button = QtWidgets.QPushButton(self.tab)
        self.del_button.setGeometry(QtCore.QRect(430, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.del_button.setFont(font)
        self.del_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(255, 128, 0);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-style: grooved;\n"
                                      "    border-width: 2px;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(255, 153, 51);\n"
                                      "}")
        self.del_button.setObjectName("del_button")
        self.minus_button = QtWidgets.QPushButton(self.tab)
        self.minus_button.setGeometry(QtCore.QRect(353, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.minus_button.setFont(font)
        self.minus_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.minus_button.setObjectName("minus_button")
        self.devide_button = QtWidgets.QPushButton(self.tab)
        self.devide_button.setGeometry(QtCore.QRect(276, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.devide_button.setFont(font)
        self.devide_button.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgb(255, 128, 0);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border-style: grooved;\n"
                                         "    border-width: 2px;\n"
                                         "    border-radius: 5px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(255, 153, 51);\n"
                                         "}")
        self.devide_button.setObjectName("devide_button")
        self.mul_button = QtWidgets.QPushButton(self.tab)
        self.mul_button.setGeometry(QtCore.QRect(353, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.mul_button.setFont(font)
        self.mul_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(255, 128, 0);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-style: grooved;\n"
                                      "    border-width: 2px;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(255, 153, 51);\n"
                                      "}")
        self.mul_button.setObjectName("mul_button")
        self.clear_button = QtWidgets.QPushButton(self.tab)
        self.clear_button.setGeometry(QtCore.QRect(430, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.clear_button.setObjectName("clear_button")
        self.zerro_button = QtWidgets.QPushButton(self.tab)
        self.zerro_button.setGeometry(QtCore.QRect(77, 306, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.zerro_button.setFont(font)
        self.zerro_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.zerro_button.setObjectName("zerro_button")
        self.go_button = QtWidgets.QPushButton(self.tab)
        self.go_button.setGeometry(QtCore.QRect(276, 229, 228, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.go_button.setFont(font)
        self.go_button.setStyleSheet("QPushButton {\n"
                                     "    background-color: rgb(255, 128, 0);\n"
                                     "    color: rgb(255, 255, 255);\n"
                                     "    border-style: grooved;\n"
                                     "    border-width: 2px;\n"
                                     "    border-radius: 5px;\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: rgb(255, 153, 51);\n"
                                     "}")
        self.go_button.setObjectName("go_button")
        self.dot_button = QtWidgets.QPushButton(self.tab)
        self.dot_button.setGeometry(QtCore.QRect(154, 306, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.dot_button.setFont(font)
        self.dot_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(255, 128, 0);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-style: grooved;\n"
                                      "    border-width: 2px;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(255, 153, 51);\n"
                                      "}")
        self.dot_button.setObjectName("dot_button")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.add_label = QtWidgets.QLabel(self.tab_2)
        self.add_label.setGeometry(QtCore.QRect(0, 0, 504, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.add_label.setFont(font)
        self.add_label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                     "background-color: rgb(255, 255, 255);\n"
                                     "border-style: solid;\n"
                                     "border-width: 3px;\n"
                                     "border-color: rgb(192, 192, 192);\n"
                                     "border-radius: 5px;\n"
                                     "")
        self.add_label.setObjectName("add_label")
        self.one_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.one_button_2.setGeometry(QtCore.QRect(0, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.one_button_2.setFont(font)
        self.one_button_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.one_button_2.setObjectName("one_button_2")
        self.two_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.two_button_2.setGeometry(QtCore.QRect(77, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.two_button_2.setFont(font)
        self.two_button_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.two_button_2.setObjectName("two_button_2")
        self.three_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.three_button_2.setGeometry(QtCore.QRect(154, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.three_button_2.setFont(font)
        self.three_button_2.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 128, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border-style: grooved;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(255, 153, 51);\n"
                                          "}")
        self.three_button_2.setObjectName("three_button_2")
        self.four_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.four_button_2.setGeometry(QtCore.QRect(0, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.four_button_2.setFont(font)
        self.four_button_2.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgb(255, 128, 0);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border-style: grooved;\n"
                                         "    border-width: 2px;\n"
                                         "    border-radius: 5px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(255, 153, 51);\n"
                                         "}")
        self.four_button_2.setObjectName("four_button_2")
        self.five_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.five_button_2.setGeometry(QtCore.QRect(77, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.five_button_2.setFont(font)
        self.five_button_2.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgb(255, 128, 0);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border-style: grooved;\n"
                                         "    border-width: 2px;\n"
                                         "    border-radius: 5px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(255, 153, 51);\n"
                                         "}")
        self.five_button_2.setObjectName("five_button_2")
        self.six_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.six_button_2.setGeometry(QtCore.QRect(154, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.six_button_2.setFont(font)
        self.six_button_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.six_button_2.setObjectName("six_button_2")
        self.seven_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.seven_button_2.setGeometry(QtCore.QRect(0, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.seven_button_2.setFont(font)
        self.seven_button_2.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 128, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border-style: grooved;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(255, 153, 51);\n"
                                          "}")
        self.seven_button_2.setObjectName("seven_button_2")
        self.eight_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.eight_button_2.setGeometry(QtCore.QRect(77, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.eight_button_2.setFont(font)
        self.eight_button_2.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 128, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border-style: grooved;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(255, 153, 51);\n"
                                          "}")
        self.eight_button_2.setObjectName("eight_button_2")
        self.nine_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.nine_button_2.setGeometry(QtCore.QRect(154, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.nine_button_2.setFont(font)
        self.nine_button_2.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgb(255, 128, 0);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border-style: grooved;\n"
                                         "    border-width: 2px;\n"
                                         "    border-radius: 5px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(255, 153, 51);\n"
                                         "}")
        self.nine_button_2.setObjectName("nine_button_2")
        self.zerro_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.zerro_button_2.setGeometry(QtCore.QRect(77, 306, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.zerro_button_2.setFont(font)
        self.zerro_button_2.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 128, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border-style: grooved;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(255, 153, 51);\n"
                                          "}")
        self.zerro_button_2.setObjectName("zerro_button_2")
        self.plius_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.plius_button_2.setGeometry(QtCore.QRect(276, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.plius_button_2.setFont(font)
        self.plius_button_2.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 128, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border-style: grooved;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(255, 153, 51);\n"
                                          "}")
        self.plius_button_2.setObjectName("plius_button_2")
        self.minus_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.minus_button_2.setGeometry(QtCore.QRect(353, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.minus_button_2.setFont(font)
        self.minus_button_2.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 128, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border-style: grooved;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(255, 153, 51);\n"
                                          "}")
        self.minus_button_2.setObjectName("minus_button_2")
        self.del_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.del_button_2.setGeometry(QtCore.QRect(430, 75, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.del_button_2.setFont(font)
        self.del_button_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.del_button_2.setObjectName("del_button_2")
        self.devide_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.devide_button_2.setGeometry(QtCore.QRect(276, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.devide_button_2.setFont(font)
        self.devide_button_2.setStyleSheet("QPushButton {\n"
                                           "    background-color: rgb(255, 128, 0);\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    border-style: grooved;\n"
                                           "    border-width: 2px;\n"
                                           "    border-radius: 5px;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: rgb(255, 153, 51);\n"
                                           "}")
        self.devide_button_2.setObjectName("devide_button_2")
        self.mul_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.mul_button_2.setGeometry(QtCore.QRect(353, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.mul_button_2.setFont(font)
        self.mul_button_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.mul_button_2.setObjectName("mul_button_2")
        self.clear_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.clear_button_2.setGeometry(QtCore.QRect(430, 152, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.clear_button_2.setFont(font)
        self.clear_button_2.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 128, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border-style: grooved;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(255, 153, 51);\n"
                                          "}")
        self.clear_button_2.setObjectName("clear_button_2")
        self.floor_dev_button = QtWidgets.QPushButton(self.tab_2)
        self.floor_dev_button.setGeometry(QtCore.QRect(276, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.floor_dev_button.setFont(font)
        self.floor_dev_button.setStyleSheet("QPushButton {\n"
                                            "    background-color: rgb(255, 128, 0);\n"
                                            "    color: rgb(255, 255, 255);\n"
                                            "    border-style: grooved;\n"
                                            "    border-width: 2px;\n"
                                            "    border-radius: 5px;\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(255, 153, 51);\n"
                                            "}")
        self.floor_dev_button.setObjectName("floor_dev_button_2")
        self.mod_button = QtWidgets.QPushButton(self.tab_2)
        self.mod_button.setGeometry(QtCore.QRect(353, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.mod_button.setFont(font)
        self.mod_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(255, 128, 0);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-style: grooved;\n"
                                      "    border-width: 2px;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(255, 153, 51);\n"
                                      "}")
        self.mod_button.setObjectName("mod_button_2")
        self.power_button = QtWidgets.QPushButton(self.tab_2)
        self.power_button.setGeometry(QtCore.QRect(430, 229, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.power_button.setFont(font)
        self.power_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.power_button.setObjectName("power_button_2")
        self.go_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.go_button_2.setGeometry(QtCore.QRect(276, 306, 228, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.go_button_2.setFont(font)
        self.go_button_2.setStyleSheet("QPushButton {\n"
                                       "    background-color: rgb(255, 128, 0);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    border-style: grooved;\n"
                                       "    border-width: 2px;\n"
                                       "    border-radius: 5px;\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(255, 153, 51);\n"
                                       "}")
        self.go_button_2.setObjectName("go_button_2")
        self.dot_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.dot_button_2.setGeometry(QtCore.QRect(154, 306, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.dot_button_2.setFont(font)
        self.dot_button_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(255, 128, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-style: grooved;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(255, 153, 51);\n"
                                        "}")
        self.dot_button_2.setObjectName("dot_button_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "py_calculator"))
        self.main_label.setText(_translate("MainWindow", "0"))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.two_button.setText(_translate("MainWindow", "2"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.plius_button.setText(_translate("MainWindow", "+"))
        self.del_button.setText(_translate("MainWindow", "DEL"))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.devide_button.setText(_translate("MainWindow", "/"))
        self.mul_button.setText(_translate("MainWindow", "*"))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.zerro_button.setText(_translate("MainWindow", "0"))
        self.go_button.setText(_translate("MainWindow", "="))
        self.dot_button.setText(_translate("MainWindow", "."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ordinary"))
        self.add_label.setText(_translate("MainWindow", "0"))
        self.one_button_2.setText(_translate("MainWindow", "1"))
        self.two_button_2.setText(_translate("MainWindow", "2"))
        self.three_button_2.setText(_translate("MainWindow", "3"))
        self.four_button_2.setText(_translate("MainWindow", "4"))
        self.five_button_2.setText(_translate("MainWindow", "5"))
        self.six_button_2.setText(_translate("MainWindow", "6"))
        self.seven_button_2.setText(_translate("MainWindow", "7"))
        self.eight_button_2.setText(_translate("MainWindow", "8"))
        self.nine_button_2.setText(_translate("MainWindow", "9"))
        self.zerro_button_2.setText(_translate("MainWindow", "0"))
        self.plius_button_2.setText(_translate("MainWindow", "+"))
        self.minus_button_2.setText(_translate("MainWindow", "-"))
        self.del_button_2.setText(_translate("MainWindow", "DEL"))
        self.devide_button_2.setText(_translate("MainWindow", "/"))
        self.mul_button_2.setText(_translate("MainWindow", "*"))
        self.clear_button_2.setText(_translate("MainWindow", "C"))
        self.floor_dev_button.setText(_translate("MainWindow", "//"))
        self.mod_button.setText(_translate("MainWindow", "%"))
        self.power_button.setText(_translate("MainWindow", "**"))
        self.go_button_2.setText(_translate("MainWindow", "="))
        self.dot_button_2.setText(_translate("MainWindow", "."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Additional"))

    def add_functions(self):
        self.one_button.clicked.connect(
            lambda: self.write_number(text=self.one_button.text(), obj_name=self.one_button.objectName()))
        self.one_button_2.clicked.connect(
            lambda: self.write_number(text=self.one_button_2.text(), obj_name=self.one_button_2.objectName()))
        self.two_button.clicked.connect(
            lambda: self.write_number(text=self.two_button.text(), obj_name=self.two_button.objectName()))
        self.two_button_2.clicked.connect(
            lambda: self.write_number(text=self.two_button_2.text(), obj_name=self.two_button_2.objectName()))
        self.three_button.clicked.connect(
            lambda: self.write_number(text=self.three_button.text(), obj_name=self.three_button.objectName()))
        self.three_button_2.clicked.connect(
            lambda: self.write_number(text=self.three_button_2.text(), obj_name=self.three_button_2.objectName()))
        self.four_button.clicked.connect(
            lambda: self.write_number(text=self.four_button.text(), obj_name=self.four_button_2.objectName()))
        self.four_button_2.clicked.connect(
            lambda: self.write_number(text=self.four_button_2.text(), obj_name=self.four_button_2.objectName()))
        self.five_button.clicked.connect(
            lambda: self.write_number(text=self.five_button.text(), obj_name=self.five_button.objectName()))
        self.five_button_2.clicked.connect(
            lambda: self.write_number(text=self.five_button_2.text(), obj_name=self.five_button_2.objectName()))
        self.six_button.clicked.connect(
            lambda: self.write_number(text=self.six_button.text(), obj_name=self.six_button.objectName()))
        self.six_button_2.clicked.connect(
            lambda: self.write_number(text=self.six_button_2.text(), obj_name=self.six_button_2.objectName()))
        self.seven_button.clicked.connect(
            lambda: self.write_number(text=self.seven_button.text(), obj_name=self.seven_button.objectName()))
        self.seven_button_2.clicked.connect(
            lambda: self.write_number(text=self.seven_button_2.text(), obj_name=self.seven_button_2.objectName()))
        self.eight_button.clicked.connect(
            lambda: self.write_number(text=self.eight_button.text(), obj_name=self.eight_button.objectName()))
        self.eight_button_2.clicked.connect(
            lambda: self.write_number(text=self.eight_button_2.text(), obj_name=self.eight_button_2.objectName()))
        self.nine_button.clicked.connect(
            lambda: self.write_number(text=self.nine_button.text(), obj_name=self.nine_button.objectName()))
        self.nine_button_2.clicked.connect(
            lambda: self.write_number(text=self.nine_button_2.text(), obj_name=self.nine_button_2.objectName()))
        self.zerro_button.clicked.connect(
            lambda: self.write_number(text=self.zerro_button.text(), obj_name=self.zerro_button.objectName()))
        self.zerro_button_2.clicked.connect(
            lambda: self.write_number(text=self.zerro_button_2.text(), obj_name=self.four_button_2.objectName()))
        self.dot_button.clicked.connect(
            lambda: self.write_number(text=self.dot_button.text(), obj_name=self.dot_button.objectName()))
        self.dot_button_2.clicked.connect(
            lambda: self.write_number(text=self.dot_button_2.text(), obj_name=self.dot_button_2.objectName()))
        self.plius_button.clicked.connect(
            lambda: self.write_number(text=self.plius_button.text(), obj_name=self.plius_button.objectName()))
        self.plius_button_2.clicked.connect(
            lambda: self.write_number(text=self.plius_button_2.text(), obj_name=self.plius_button_2.objectName()))
        self.minus_button.clicked.connect(
            lambda: self.write_number(text=self.minus_button.text(), obj_name=self.minus_button.objectName()))
        self.minus_button_2.clicked.connect(
            lambda: self.write_number(text=self.minus_button_2.text(), obj_name=self.minus_button_2.objectName()))
        self.devide_button.clicked.connect(
            lambda: self.write_number(text=self.devide_button.text(), obj_name=self.devide_button.objectName()))
        self.devide_button_2.clicked.connect(
            lambda: self.write_number(text=self.devide_button_2.text(), obj_name=self.devide_button_2.objectName()))
        self.mul_button.clicked.connect(
            lambda: self.write_number(text=self.mul_button.text(), obj_name=self.mul_button.objectName()))
        self.mul_button_2.clicked.connect(
            lambda: self.write_number(text=self.mul_button_2.text(), obj_name=self.mul_button_2.objectName()))
        self.floor_dev_button.clicked.connect(
            lambda: self.write_number(text=self.floor_dev_button.text(), obj_name=self.floor_dev_button.objectName()))
        self.power_button.clicked.connect(
            lambda: self.write_number(text=self.power_button.text(), obj_name=self.power_button.objectName()))
        self.mod_button.clicked.connect(
            lambda: self.write_number(text=self.mod_button.text(), obj_name=self.mod_button.objectName()))
        self.del_button.clicked.connect(
            lambda: self.dell_symbol_in_main_label())
        self.del_button_2.clicked.connect(
            lambda: self.dell_symbol_in_add_label())
        self.clear_button.clicked.connect(lambda: self.clear_main())
        self.clear_button_2.clicked.connect(lambda: self.clear_add())
        self.go_button.clicked.connect(lambda: self.calc_the_result_for_main_label())
        self.go_button_2.clicked.connect(lambda: self.calc_the_result_for_add_label())

    def write_number(self, text='', obj_name=''):
        if obj_name.__contains__('2'):
            if self.add_label.text() == '0' or self.is_equal:
                self.add_label.setText(text)
                self.is_equal = False
                return
            if self.add_label.text() == '0' and text == '.':
                self.add_label.setText(self.add_label.text() + text)
            elif self.add_label.text() == '0' or self.add_label.text() == 'SyntaxError' or self.add_label.text() == 'ZeroDivisionError':
                self.add_label.setText(text)
            else:
                self.add_label.setText(self.add_label.text() + text)
        else:
            if self.main_label.text() == '0' or self.is_equal:
                self.main_label.setText(text)
                self.is_equal = False
                return
            if self.main_label.text() == '0' and text == '.':
                self.main_label.setText(self.main_label.text() + text)
            elif self.main_label.text() == '0' or self.main_label.text() == 'SyntaxError' or self.add_label.text() == 'ZeroDivisionError':
                self.main_label.setText(text)
            else:
                self.main_label.setText(self.main_label.text() + text)

    def calc_the_result_for_main_label(self):
        try:
            res = eval(self.main_label.text())
            self.main_label.setText(str(res))
            self.is_equal = True
        except ZeroDivisionError:
            self.main_label.setText('ZeroDivisionError')
        except SyntaxError:
            self.main_label.setText('SyntaxError')

    def calc_the_result_for_add_label(self):
        try:
            res = eval(self.add_label.text())
            self.add_label.setText(str(res))
            self.is_equal = True
        except ZeroDivisionError:
            self.main_label.setText("ZeroDivisionError")
        except SyntaxError:
            self.main_label.setText('SyntaxError')

    def clear_main(self):
        self.main_label.setText('0')  # clears the main label

    def clear_add(self):
        self.add_label.setText('0')  # clears the additional label

    def dell_symbol_in_main_label(self):
        if self.main_label.text() == 'ZeroDivisionError' or self.main_label.text() == 'SyntaxError':
            self.clear_main()
        elif self.main_label.text() == '0':
            pass
        else:
            self.main_label.setText(self.main_label.text()[:-1])

    def dell_symbol_in_add_label(self):
        if self.add_label.text() == 'ZeroDivisionError' or self.add_label.text() == 'SyntaxError':
            self.clear_add()
        elif self.add_label.text() == '0':
            pass
        else:
            self.add_label.setText(self.add_label.text()[:-1])


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
